[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."updateReaction"]
  external_node_modules = ["airtable"]

[functions."LetterApproved"]
node_bundler = "esbuild"

[build.environment]
  AIRTABLE_TOKEN = ""
